-- 1. Game Configuration Table
-- Stores the rules and setting of the universe.
DROP TABLE IF EXISTS game_config;
CREATE TABLE game_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Insert initial values for a sci-fi galactic setting.
INSERT INTO game_config (key, value) VALUES
('system_prompt', 'You act as a Game Master (GM) for a sci-fi RPG. Your task is to narrate events, resolve actions, and maintain universe coherence. Always respond with a JSON containing "narrative" and "updates".'),
('world_description', 'The known universe is in a fragile peace under the watchful eye of the Star Consortium. Megacorporations, criminal syndicates, and ancient alien factions compete for power in the shadows. Technology has advanced by leaps and bounds, but the galaxy remains a dangerous place full of mysteries.'),
('rules', '1. Actions are resolved based on character attributes (Strength, Agility, Intellect, Tech, Presence, Will) on a scale of 1 to 20. A higher score increases the probability of success.\n2. The GM (AI) has the final say on the outcome of an action, considering attributes and the situation.\n3. There is no health system (HP) or dice. Success is based on description and attribute logic.');

-- 2. Players Table
-- Contains all player characters, authentication, and faction data.
DROP TABLE IF EXISTS players;
CREATE TABLE players (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, -- For authentication
    faccion_nombre TEXT,    -- Faction name
    banner_url TEXT,        -- URL or Base64 string for the faction banner
    stats_json JSONB,       -- Biography and attributes
    -- Example of stats_json:
    -- {
    --   "biografia": {
    --     "nombre": "Zane Krios",
    --     "raza": "Humano modificado",
    --     "edad": 35,
    --     "sexo": "Masculino"
    --   },
    --   "atributos": {
    --     "fuerza": 12,
    --     "agilidad": 16,
    --     "intelecto": 14,
    --     "tecnica": 18,
    --     "presencia": 10,
    --     "voluntad": 15
    --   }
    -- }
    estado TEXT DEFAULT 'Activo',
    ubicacion TEXT
);

-- 3. Event Logs Table
-- Records the narrative generated by the GM.
DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
    id SERIAL PRIMARY KEY,
    turno INTEGER,
    evento_texto TEXT NOT NULL,
    prompt_imagen TEXT
);
