-- sql/update_market_system.sql

CREATE TABLE IF NOT EXISTS market_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL, -- 'materiales', 'componentes', etc.
    amount INTEGER NOT NULL,     -- Positivo = Compra, Negativo = Venta
    price_per_unit INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'COMPLETED', 'CANCELLED'
    created_at_tick INTEGER NOT NULL,
    processed_at_tick INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_market_orders_player_status ON market_orders(player_id, status);